<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Bewakoof" duration-ms="40406" started-at="2020-01-02T23:53:05 IST" finished-at="2020-01-02T23:53:45 IST">
    <groups>
    </groups>
    <test name="SignUp_DDT" duration-ms="40406" started-at="2020-01-02T23:53:05 IST" finished-at="2020-01-02T23:53:45 IST">
      <class name="com.bewkoof.testCases.TC_SignUp_DDT_004">
        <test-method status="PASS" signature="launchBrowser(java.lang.String)[pri:0, instance:com.bewkoof.testCases.TC_SignUp_DDT_004@3701eaf6]" name="launchBrowser" is-config="true" duration-ms="12719" started-at="2020-01-02T23:53:05 IST" description="Launch Browser" finished-at="2020-01-02T23:53:18 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="FAIL" signature="createAccountOnBewakoof(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.bewkoof.testCases.TC_SignUp_DDT_004@3701eaf6]" name="createAccountOnBewakoof" duration-ms="8330" started-at="2020-01-02T23:53:20 IST" description="Sign Up Into Bewakoof " data-provider="Bewakoof Data" finished-at="2020-01-02T23:53:28 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Khusbhoo]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Tanwar]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[7002589645]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[khusbhootanwar54@gmail.com]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[zxcvbnm123]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[Female]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[ Test Failed Becasue may be mobile number,mailId is already used did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError:  Test Failed Becasue may be mobile number,mailId is already used did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at com.bewkoof.testCases.TC_SignUp_DDT_004.createAccountOnBewakoof(TC_SignUp_DDT_004.java:91)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createAccountOnBewakoof -->
        <test-method status="FAIL" signature="createAccountOnBewakoof(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.bewkoof.testCases.TC_SignUp_DDT_004@3701eaf6]" name="createAccountOnBewakoof" duration-ms="8694" started-at="2020-01-02T23:53:28 IST" description="Sign Up Into Bewakoof " data-provider="Bewakoof Data" finished-at="2020-01-02T23:53:37 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Abishek]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Rathore]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[9200789489]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[abishekrathore020@gmail.com]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[asdfghjkl123]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[male]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[ Test Failed Becasue may be mobile number,mailId is already used did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError:  Test Failed Becasue may be mobile number,mailId is already used did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at com.bewkoof.testCases.TC_SignUp_DDT_004.createAccountOnBewakoof(TC_SignUp_DDT_004.java:91)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createAccountOnBewakoof -->
        <test-method status="FAIL" signature="createAccountOnBewakoof(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.bewkoof.testCases.TC_SignUp_DDT_004@3701eaf6]" name="createAccountOnBewakoof" duration-ms="8011" started-at="2020-01-02T23:53:37 IST" description="Sign Up Into Bewakoof " data-provider="Bewakoof Data" finished-at="2020-01-02T23:53:45 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Mittal]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Surotiya]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[7888998998]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[bannanittal789@gmail.com]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[123654987]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[Male]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[ Test Failed Becasue may be mobile number,mailId is already used did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError:  Test Failed Becasue may be mobile number,mailId is already used did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at com.bewkoof.testCases.TC_SignUp_DDT_004.createAccountOnBewakoof(TC_SignUp_DDT_004.java:91)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createAccountOnBewakoof -->
        <test-method status="PASS" signature="closeBrowser(java.lang.String)[pri:0, instance:com.bewkoof.testCases.TC_SignUp_DDT_004@3701eaf6]" name="closeBrowser" is-config="true" duration-ms="819" started-at="2020-01-02T23:53:45 IST" description="Close Browser" finished-at="2020-01-02T23:53:45 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.bewkoof.testCases.TC_SignUp_DDT_004 -->
    </test> <!-- SignUp_DDT -->
  </suite> <!-- Bewakoof -->
</testng-results>
